name: PHPCPD

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.php'
      - '.github/workflows/phpcpd.yml'
  push:
    branches:
      - develop
    paths:
      - '**.php'
      - '.github/workflows/phpcpd.yml'
  workflow_call:
    inputs:
      dirs:
        description: Directories to check
        required: true
        type: string
      options:
        description: Options to phpcpd
        required: false
        type: string
      php-version:
        required: false
        type: string
        default: '8.2'

permissions:
  contents: read

jobs:
  build:
    name: Code Copy-Paste Detection
    runs-on: ubuntu-latest
    if: (! contains(github.event.head_commit.message, '[ci skip]'))

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs['php-version'] }}
          tools: phpcpd
          extensions: dom, mbstring
          coverage: none

      - name: Detect duplicate code
        run: phpcpd ${{ inputs.dirs }} ${{ inputs.options }}
